SELECT * FROM EMPLEADO_PARCIAL;
SELECT * FROM ESTRATO_PARCIAL;
SELECT * FROM CARGO_PARCIAL;
SELECT * FROM SEDE_PARCIAL;

ALTER TABLE EMPLEADO_PARCIAL SET UNUSED COLUMN ID;
ALTER TABLE EMPLEADO_PARCIAL DROP UNUSED COLUMNS;
ALTER TABLE EMPLEADO_PARCIAL ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (CC);

ALTER TABLE ESTRATO_PARCIAL SET UNUSED COLUMN ID;
ALTER TABLE ESTRATO_PARCIAL DROP UNUSED COLUMNS;
ALTER TABLE ESTRATO_PARCIAL ADD CONSTRAINT PK_ESTRATO PRIMARY KEY (ID_ESTRATO);

ALTER TABLE CARGO_PARCIAL SET UNUSED COLUMN ID;
ALTER TABLE CARGO_PARCIAL DROP UNUSED COLUMNS;
ALTER TABLE CARGO_PARCIAL ADD CONSTRAINT PK_CARGO PRIMARY KEY (ID_CARGO);

ALTER TABLE SEDE_PARCIAL SET UNUSED COLUMN ID;
ALTER TABLE SEDE_PARCIAL DROP UNUSED COLUMNS;
ALTER TABLE SEDE_PARCIAL ADD CONSTRAINT PK_SEDE PRIMARY KEY (ID_SEDE);

ALTER TABLE EMPLEADO_PARCIAL ADD CONSTRAINT FK_EMPLEADO_ESTRATO FOREIGN KEY (ID_ESTRATO) REFERENCES ESTRATO_PARCIAL;
ALTER TABLE EMPLEADO_PARCIAL ADD CONSTRAINT FK_EMPLEADO_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO_PARCIAL;
ALTER TABLE EMPLEADO_PARCIAL ADD CONSTRAINT FK_EMPLEADO_SEDE FOREIGN KEY (ID_SEDE) REFERENCES SEDE_PARCIAL;

SELECT COUNT(*) FROM EMPLEADO_PARCIAL;
-- 452

SELECT ID_SEDE, COUNT(*) FROM EMPLEADO_PARCIAL GROUP BY ID_SEDE;
-- NORTE 80
-- CENTRO 79 
-- SUR 79
-- OCCIDENTE 135
-- ORIENTE 79

SELECT ID_ESTRATO, COUNT(*) FROM EMPLEADO_PARCIAL GROUP BY ID_ESTRATO;
-- 1 67
-- 2 68
-- 3 68
-- 4 68
-- 5 90
-- 6 91

-- MAS ANTIGUO
SELECT NOMBRES, FECHA_DE_CONTRATACION FROM EMPLEADO_PARCIAL WHERE FECHA_DE_CONTRATACION=(SELECT MIN(FECHA_DE_CONTRATACION) FROM EMPLEADO_PARCIAL);
-- MARIO FERNANDO 02/01/1991

-- MAS NUEVO
SELECT NOMBRES, FECHA_DE_CONTRATACION FROM EMPLEADO_PARCIAL WHERE FECHA_DE_CONTRATACION=(SELECT MAX(FECHA_DE_CONTRATACION) FROM EMPLEADO_PARCIAL);
-- MARIO ANDRES 02/01/2014

SELECT EMPLEADO_PARCIAL.NOMBRES, SEDE_PARCIAL.NOMBRE_SEDE, CARGO_PARCIAL.NOMBRE_CARGO FROM EMPLEADO_PARCIAL JOIN SEDE_PARCIAL ON EMPLEADO_PARCIAL.ID_SEDE = SEDE_PARCIAL.ID_SEDE  JOIN CARGO_PARCIAL ON EMPLEADO_PARCIAL.ID_CARGO = CARGO_PARCIAL.ID_CARGO WHERE EMPLEADO_PARCIAL.CC ='10662101';
-- HECTOR ALBERTO	NORTE	CONTADOR

--  BORRAR HABEAS DATA
DELETE FROM EMPLEADO_PARCIAL WHERE EMPLEADO_PARCIAL.CC ='10188530';

SELECT NOMBRES, FECHA_DE_CONTRATACION FROM EMPLEADO_PARCIAL WHERE FECHA_DE_CONTRATACION BETWEEN '01/01/2000' AND '12/31/2005';

SELECT NOMBRES, EDAD FROM EMPLEADO_PARCIAL ORDER BY NOMBRES DESC;

SELECT NOMBRES, EDAD FROM EMPLEADO_PARCIAL WHERE EDAD BETWEEN 17 AND 25;

SELECT AVG(EDAD) FROM EMPLEADO_PARCIAL;
-- 43.23 Edad promedio

SELECT sum(SUELDO) FROM EMPLEADO_PARCIAL;
-- 1109093197

SELECT EMPLEADO_PARCIAL.NOMBRES, EMPLEADO_PARCIAL.FECHA_DE_CONTRATACION, ESTRATO_PARCIAL.NOMBRE_ESTRATO, SEDE_PARCIAL.NOMBRE_SEDE, CARGO_PARCIAL.NOMBRE_CARGO FROM EMPLEADO_PARCIAL JOIN SEDE_PARCIAL ON EMPLEADO_PARCIAL.ID_SEDE = SEDE_PARCIAL.ID_SEDE  JOIN CARGO_PARCIAL ON EMPLEADO_PARCIAL.ID_CARGO = CARGO_PARCIAL.ID_CARGO JOIN ESTRATO_PARCIAL ON EMPLEADO_PARCIAL.ID_ESTRATO = ESTRATO_PARCIAL.ID_ESTRATO WHERE EMPLEADO_PARCIAL.SUELDO=(SELECT MAX(EMPLEADO_PARCIAL.SUELDO) FROM EMPLEADO_PARCIAL);
-- FLOR YOLANDA	01/01/1999	ESTRATO 4	ORIENTE	SISTEMAS

SELECT NOMBRES FROM EMPLEADO_PARCIAL WHERE EDAD=(SELECT MIN(EDAD) FROM EMPLEADO_PARCIAL) AND ID_SEDE=3 fetch first 1 row only;

SELECT ESTRATO_PARCIAL.NOMBRE_ESTRATO, COUNT(*) AS EMPLEADOS FROM EMPLEADO_PARCIAL JOIN ESTRATO_PARCIAL ON EMPLEADO_PARCIAL.ID_ESTRATO = ESTRATO_PARCIAL.ID_ESTRATO GROUP BY NOMBRE_ESTRATO ORDER BY NOMBRE_ESTRATO;
-- 

SELECT SEDE_PARCIAL.NOMBRE_SEDE, COUNT(*) AS EMPLEADOS FROM EMPLEADO_PARCIAL JOIN SEDE_PARCIAL ON EMPLEADO_PARCIAL.ID_SEDE = SEDE_PARCIAL.ID_SEDE GROUP BY NOMBRE_SEDE ORDER BY NOMBRE_SEDE;